import { StyleSheet } from 'react-native';

export const COLORS = {
  primary: '#1A1A1A',
  secondary: '#F5F5F5',
  accent: '#D4AF37',
  white: '#FFFFFF',
  text: '#333333',
  textLight: '#888888',
};

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.white },
  content: { flex: 1, padding: 24, justifyContent: 'center' },
  headerTitle: { fontSize: 32, fontWeight: '800', color: COLORS.primary, marginBottom: 8 },
  screenTitle: { fontSize: 28, fontWeight: '700', color: COLORS.primary, marginBottom: 5 },
  subHeader: { fontSize: 16, color: COLORS.textLight, marginBottom: 30 },
  locationTag: { fontSize: 14, fontWeight: '600', color: COLORS.accent, marginTop: 4, textTransform: 'uppercase' },
  section: { marginBottom: 30 },
  row: { flexDirection: 'row', justifyContent: 'space-between' },
  wrapRow: { flexDirection: 'row', flexWrap: 'wrap' },
  label: { fontSize: 14, fontWeight: '700', marginBottom: 12, color: COLORS.text, textTransform: 'uppercase' },
  input: { borderBottomWidth: 1, borderBottomColor: '#E0E0E0', fontSize: 18, paddingVertical: 10, color: COLORS.primary, marginBottom: 20 },
  inputGroup: { marginBottom: 30 },
  chip: { paddingVertical: 10, paddingHorizontal: 20, borderRadius: 25, borderWidth: 1, borderColor: '#E0E0E0', marginRight: 10, marginBottom: 10, backgroundColor: COLORS.white },
  chipSelected: { backgroundColor: COLORS.primary, borderColor: COLORS.primary },
  chipText: { fontSize: 14, color: COLORS.text },
  chipTextSelected: { color: COLORS.white, fontWeight: '600' },
  mainButton: { backgroundColor: COLORS.primary, paddingVertical: 18, borderRadius: 12, alignItems: 'center', marginTop: 10 },
  mainButtonText: { color: COLORS.white, fontSize: 16, fontWeight: 'bold' },
  outlineButton: { paddingVertical: 18, borderRadius: 12, alignItems: 'center', marginHorizontal: 24, marginTop: 20, borderWidth: 1, borderColor: COLORS.primary },
  outlineButtonText: { color: COLORS.primary, fontSize: 16, fontWeight: '600' },
  grid: { flexDirection: 'row', flexWrap: 'wrap', padding: 24 },
  addCard: { width: 100, height: 100, backgroundColor: '#F0F0F0', borderRadius: 12, justifyContent: 'center', alignItems: 'center', marginBottom: 15, marginRight: 15 },
  wardrobeImg: { width: 100, height: 100, borderRadius: 12, marginBottom: 15, marginRight: 15 },
  headerRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 24 },
  linkText: { color: COLORS.textLight, textDecorationLine: 'underline' },
  bodyText: { paddingHorizontal: 24, color: COLORS.textLight, marginBottom: 10 },
  headerPadding: { padding: 24, paddingBottom: 10 },
  outfitCard: { marginHorizontal: 24, marginBottom: 30, backgroundColor: COLORS.white, borderRadius: 16, shadowColor: "#000", shadowOffset: { width: 0, height: 5 }, shadowOpacity: 0.1, shadowRadius: 10, elevation: 3, overflow: 'hidden', borderWidth: 1, borderColor: '#F0F0F0' },
  outfitImage: { width: '100%', height: 250, resizeMode: 'cover' },
  cardContent: { padding: 20 },
  cardTitle: { fontSize: 20, fontWeight: '700', color: COLORS.primary, marginBottom: 5 },
  cardDesc: { fontSize: 14, color: COLORS.textLight, lineHeight: 20 },
});